open-company/open-company-storage

README.md
REPL_notes.clj
api.yml
example-report.json
project.clj
src/open_company/api/common.clj
src/open_company/api/companies.clj
src/open_company/api/reports.clj
src/open_company/app.clj
src/open_company/config.clj
src/open_company/representations/common.clj
src/open_company/representations/company.clj
src/open_company/representations/report.clj
src/open_company/resources/common.clj
src/open_company/resources/company.clj
src/open_company/resources/report.clj
src/open_company_api/core.clj
test/open_company/integration/company/company_create.clj
test/open_company/lib/check.clj
test/open_company/lib/hateoas.clj
test/open_company/lib/rest_api_mock.clj
test/open_company_api/core_test.clj

To test:
0. Follow the README to deal w/ any dependencies
1. Follow the README to create the DB and indexes
2. Follow the README to start the API
3. Follow the README to create the DB, tables and indexes at the REPL.
4. Run the cURL examples from the README.
No automatic DB setup yet. Coming soon.
No test support yet. Coming soon.
No data validation yet. Coming soon.
No default values yet. Coming soon.
No time stamps yet. Coming soon.
No cascading deletes from company to reports yet. Coming soon.
No logging yet.
No PATCH support yet.

Initial API implementation for companies and reports

---

REPL_notes.clj
src/open_company/api/companies.clj
src/open_company/api/reports.clj
src/open_company/config.clj
src/open_company/representations/company.clj
src/open_company/representations/report.clj
src/open_company/resources/company.clj
src/open_company/resources/report.clj
test/open_company/integration/company/company_create.clj
test/open_company/lib/hateoas.clj
test/open_company/lib/rest_api_mock.clj

https://trello.com/c/AnKFKbEj
Move the company and report media-types to a more logical spot. Simplified some logic in DB config. Made the stub of REST API tests pass.
To test:
Run the API server and cURL some requests, make sure everything still works OK.
Run the existing tests which now pass (if your dev DB is initialized):
```console
lein midje
```

Minor refactorings

---

README.md
project.clj
src/open_company/api/common.clj
src/open_company/api/companies.clj
src/open_company/api/reports.clj
src/open_company/db/init.clj
src/open_company/resources/common.clj
src/open_company/resources/company.clj
src/open_company/resources/report.clj
test/open_company/integration/company/company_create.clj
test/open_company/lib/check.clj
test/open_company/lib/resources.clj
test/open_company/unit/resources/company/company_create.clj
test/open_company/unit/resources/company/company_update.clj

https://trello.com/c/CCn1F0tO
In addition to the timestamp support on companies and reports, there is some cleanup to the README and some code refactoring.
To test:
Run the automated tests:
```
lein test!
```
All pass? Good!
Next, start your REPL:
```
lein repl
```
Then, run through all the steps in the REPL section of the README, paying extra attention to the `created-at` and `updated-at` fields. All seems as it should? Splendid!
Next, start your API server:
```
lein start
```
Finally, run through all the steps in the cURL section of the README, paying extra attention to the `created-at` and `updated-at` fields. All seems as it should? Great gravy! Merge this puppy.

Timestamps

---

README.md
src/open_company/api/companies.clj
src/open_company/representations/common.clj
src/open_company/representations/company.clj
src/open_company/resources/company.clj
src/open_company/resources/report.clj

https://trello.com/c/GSHh49g1
Start with no companies.
At the REPL:
```clojure
(company/list-companies)
```
Empty vector? Cool.
With cURL:
```console
curl -i -X GET --header "Accept-Charset: utf-8" http//localhost:3000/v1/companies
```
and (with trailing slash):
```console
curl -i -X GET --header "Accept-Charset: utf-8" http//localhost:3000/v1/companies/
```
Empty companies array? Groovy time.
Add some companies like OPEN and BUFFR (see README).
Repeat the REPL and cURL commands above. See a JSON Collection with companies in it that have names, symbols and GET links? It's the bee's knees! Merge.

Company list from REST API

---

README.md
REPL_notes.clj
src/open_company/resources/common.clj
src/open_company/resources/company.clj
src/open_company/resources/report.clj
test/open_company/unit/resources/company/company_update.clj

https://trello.com/c/VAWfPORI
Fix some typos in README and REPL notes.
Fix broken update code due to misunderstanding RethinkDB replace.
Change DB operations (create, update, delete, delete all) to throw exceptions for unexpected outcomes rather than return false.
DRY up resource reads, deletes and delete alls rather than having them separate in company and report.
DRY up table name and primary key references.
Normalize update so it only takes updated resource as the argument.
To test:
Run the tests:
```console
lein test!
```
Run through the entire REPL and cURL sequence in the README.

DB Improvements

---

src/open_company/resources/report.clj

review with: https://github.com/open-company/open-company-web/pull/16
This is needed to let the API accept these periods: Q[1-4] M[1-12] W[1-52]

automatic generate period strings

---

opt/samples/buffer.edn
project.clj
src/open_company/resources/common.clj
src/open_company/resources/company.clj
src/open_company/resources/section.clj
src/open_company/util/sample_data.clj

https://trello.com/c/q19XPoho
To test:
Make sure lein is 2.5.3+
Run `lein run -m open-company.util.sample-data -- -d ./opt/samples/buffer.edn` locally.
Then get Buffer through cURL or REPL or web UI (will only see some sections).
Do you see sections for: values, mission, growth, finances, update, asks, product and team?
Do you see 2 older revisions for all but values and mission?
Groovy.... merge, deploy to staging, and put the clean Buffer data on staging with:
`lein with-profile prod run -m open-company.util.sample-data -- -d ./opt/samples/buffer.edn`
Does the Buffer data on staging look just as swanky? Good!
Eat an Oreo dipped in cold milk. Ponder the universe whilst chewing.

Sample data import script, and sample data for Buffer

---

README.md
docs/example-company-only-finance.json
docs/example-company.json
opt/samples/buffer.edn
opt/samples/mature.edn
opt/samples/new.edn
opt/samples/yoyo.edn
project.clj
src/open_company/api/common.clj
src/open_company/api/companies.clj
src/open_company/api/sections.clj
src/open_company/config.clj
src/open_company/lib/jwt.clj
src/open_company/resources/common.clj
src/open_company/resources/company.clj
src/open_company/resources/section.clj
src/open_company/util/sample_data.clj

https://trello.com/c/PyfjkhgZ
To test:
Make some normal API requests with no authorization, note you get a 401:
```
curl -i -X GET http://localhost:3000/companies
```
```
curl -i -X GET http://localhost:3000/companies/buffer
```
Now make the same API calls as a logged in user in the UI which passes JWT credentials and note that you can see the company list and the buffer data.
Now edit one of the text sections of the buffer data. Then refresh the page (there's a UI bug) and see that the update was attributed to your logged in user. Pull the same section from the Clojure API and see that the `:author` is you:
```clojure
(section/get-company "buffer" "update")
```
Next rerun the sample data import (with delete flag) for `buffer.edn`, `mature.edn`, `new.edn` and `yoyo.edn`. Notice they have …

Section update authorship

---

README.md
opt/samples/buffer.edn
opt/samples/ent.edn
opt/samples/new.edn
opt/samples/yoyo.edn
src/open_company/api/companies.clj
src/open_company/api/sections.clj
src/open_company/resources/common.clj
src/open_company/resources/company.clj
src/open_company/resources/section.clj
test/open_company/integration/section/section_manipulation.clj
test/open_company/lib/rest_api_mock.clj
test/open_company/unit/resources/company/company_create.clj
test/open_company/unit/resources/section/section_revision.clj

https://trello.com/c/y3utBhod
This PR adds support for PATCHING the :sections property of a company to support reordering and removing sections.
To test:
0. Review the codes
1. Review the `./integration/section/section_manipulation.clj` tests
2. Execute all the tests with `lein test!` (or look at the CI results)
3. Run the cURL command from the README that has you reorder Buffer's sections. Then GET buffer (or use the UI) and confirm that the sections are reordered.
3. Run the cURL command from the README that has you remove a section (marketing) from Buffer. Then GET buffer (or use the UI) and confirm that the section is removed.
5. Merge
6. Go build a reorder section and remove section UI in the ToC
7. Learn Japanese

Section manipulation

---

docs/api.md
docs/example-company-only-finance.json
docs/example-company.json
opt/samples/buffer.edn
opt/samples/ent.edn
opt/samples/new.edn
opt/samples/yoyo.edn
project.clj
src/open_company/api/companies.clj
src/open_company/app.clj
src/open_company/assets/sections.json
src/open_company/representations/company.clj
src/open_company/resources/common.clj
test/open_company/integration/section/section_manipulation.clj
test/open_company/lib/hateoas.clj
test/open_company/unit/resources/company/company_create.clj

https://trello.com/c/J9pqqyNF
To test:
0. Review the code carefully
1. cURL w/ a JWToken to `/companies/buffer/section/new`, got a dump of the JSON file at `./assets/sections.json`? Good!
2. cURL w/o a JWToken to `/companies/buffer/section/new`, got a 401? Good!
3. cURL w/ a JWToken to `/companies/buffer/section/new`, got a 404? Good!
4. Merge
5. Stare at the sun for 10 seconds.

Add an endpoint for new section list

---

README.md
src/open_company/api/companies.clj
src/open_company/resources/common.clj
src/open_company/resources/company.clj

https://trello.com/c/Ru63StZS
To test:
Using the UI, add a section.
Does it work right? Look at the `PATCH` response, does the new section have `author` and timestamps? Look in the RethinkDB database, does the sections table have the new section? Does it look just like all the other sections in there that came from the import?
Groovy. Review the code. Merge. Learn the blues harmonica.

Section add fix

---

.gitignore
opt/samples/bago.edn
opt/samples/buffer.edn
opt/samples/pied-piper.edn
opt/samples/simple.edn
src/open_company/assets/sections.json

Review with https://github.com/open-company/open-company-web/pull/55

Growth editing

---

src/open_company/api/entry.clj
src/open_company/app.clj
src/open_company/db/init.clj
src/open_company/resources/company.clj
test/open_company/integration/entry.clj
test/open_company/lib/resources.clj
test/open_company/unit/resources/company/company_list.clj

card: https://trello.com/c/wQXEbxey
See comments in the entry namespace for some potential discussion points.

Add entry point routes "/"

---

project.clj
src/dev.clj
src/open_company/api/sections.clj
src/open_company/app.clj
src/open_company/components.clj
src/open_company/config.clj

This fixes problems with indefinite blocking during startup

Rename user namespace to dev

---

src/open_company/resources/common.clj

380 minor ui issues

---

opt/samples/bago.edn
opt/samples/blank.edn
opt/samples/buffer.edn
opt/samples/ent.edn
opt/samples/new.edn
opt/samples/pied-piper.edn
opt/samples/read-only.edn
opt/samples/simple.edn
opt/samples/uni.edn
opt/samples/yoyo.edn
src/open_company/api/common.clj
src/open_company/api/companies.clj
src/open_company/api/sections.clj
src/open_company/representations/company.clj
src/open_company/resources/common.clj
src/open_company/resources/company.clj
test/open_company/integration/company/company_list.clj
test/open_company/integration/company/company_retrieval.clj
test/open_company/lib/resources.clj

[trello card](https://trello.com/c/3YCjj2eK/427-public-private-company-toggle) — WEB PR: https://github.com/open-company/open-company-web/pull/143
Test steps in Web PR.

427 public private company toggle

---

src/open_company/api/common.clj
src/open_company/api/stakeholder_updates.clj
src/open_company/lib/bot.clj
src/open_company/resources/common.clj
src/open_company/resources/stakeholder_update.clj
test/open_company/integration/company/company_create.clj

Review with https://github.com/open-company/open-company-bot/pull/9 — [trello card](https://trello.com/c/qa0oG1yl/416-slack-share-snapshot-end-to-end-api-bot)
**Test instructions in other PR**

Stakeholder Updates via Bot

---

opt/samples/bago.edn
opt/samples/blank.edn
opt/samples/buff.edn
opt/samples/ent.edn
opt/samples/green-labs.edn
opt/samples/new.edn
opt/samples/read-only.edn
opt/samples/simple.edn
opt/samples/uni.edn
opt/samples/yoyo.edn
src/open_company/db/migrations/1475231548177_update_slack_org_ids.edn

Bounce your API server on this branch to run the new migration. Watch the output. Everything migrated OK?
Open `/` in your web app. Do you get sent to `/companies`? Normal sample/OC companies there?
Import sample companies. Repeat web tests above. All good?
NB: This has already been deployed on staging.
NB: This should only be merged into mainline and NOT be merged into master yet and deployed on beta. Needs to go out as a batch with other email/auth changes.

Update Slack org-id prefix in data.

---

src/open_company/api/stakeholder_updates.clj
src/open_company/representations/stakeholder_update.clj

Review with: https://github.com/open-company/open-company-web/pull/206
This PR add a link to the company in a stakeholder-update response only if the company is public or if the user is part of the org.

Stakeholder company link

---

project.clj
src/oc/storage/api/entries.clj
src/oc/storage/api/orgs.clj
src/oc/storage/config.clj
src/oc/storage/representations/entry.clj
src/oc/storage/representations/media_types.clj
src/oc/storage/resources/board.clj
src/oc/storage/resources/common.clj
src/oc/storage/resources/entry.clj
src/oc/storage/resources/org.clj
src/oc/storage/resources/update.clj
test/open_company/unit/resources/section/section_revision.clj

https://trello.com/c/1nSMPGVJ
In addition to this PR:
Main review is mainline of here:
https://github.com/open-company/open-company-interaction
Supporting oc.lib PR:
https://github.com/open-company/open-company-lib/pull/9
Supporting infrastructure PR:
https://github.com/belucid/open-company-infrastructure/pull/38
This is mainly a code review. The functionality/QA review will happen via the web client PR.

Interactions

---

project.clj

Main PR: https://github.com/open-company/open-company-auth/pull/18

Stacked slack permissions

---

project.clj

This PR is needed only to upgrade the lib version at the same time of all the other services or the JWT coming with new versions will be rejected because they may have fields not valid in the old Claims.
Main PR: https://github.com/open-company/open-company-web/pull/244

Base ML UI

---

resources/default-new-org.edn

https://trello.com/c/B4aeEOPH
Just adds back in board/post/comment content which we've had blank for a while.

NUX board/post content.

---

src/oc/storage/api/boards.clj
src/oc/storage/api/entries.clj

Trello: https://trello.com/c/4vr18DK7/1220-support-move-to-sections
To test create a new post and add a new section to this post. 
Repeat step one but turn on slack mirroring.

Sns message

---

src/oc/storage/api/boards.clj
src/oc/storage/api/entries.clj
src/oc/storage/async/email.clj
src/oc/storage/async/notification.clj

Email personal notes

---

README.md
project.clj
src/oc/storage/app.clj
src/oc/storage/config.clj
src/oc/storage/representations/org.clj

Remove whats new related code.

---

src/oc/storage/api/entries.clj
src/oc/storage/async/bot.clj

Test with https://github.com/open-company/open-company-bot/pull/29

Pass on needed info to unfurl slack share.

---

src/oc/storage/api/boards.clj
src/oc/storage/api/entries.clj
src/oc/storage/api/orgs.clj
src/oc/storage/representations/board.clj
src/oc/storage/resources/board.clj
src/oc/storage/resources/common.clj
src/oc/storage/resources/entry.clj

Draft to new section

---

project.clj

Version bump for open company lib.

need jwt token validation for google

---

README.md
src/dev.clj
src/oc/storage/app.clj
src/oc/storage/async/auth_notification.clj
src/oc/storage/components.clj
src/oc/storage/config.clj

Used to support https://github.com/open-company/open-company-auth/pull/52

Adds a new user as an author when an SNS message is recieved.

---

src/oc/storage/representations/entry.clj
src/oc/storage/resources/common.clj
src/oc/storage/resources/entry.clj

Needed to support displaying the image with our own play button.

Store video image from Ziggeo

---

project.clj

Main PR https://github.com/open-company/open-company-lib/pull/38

Upgrade oc lib to latest version.

---

src/oc/storage/async/bot.clj
src/oc/storage/async/email.clj

Main PR: https://github.com/open-company/open-company-digest/pull/8

Add Must see and Video to digest

---

src/oc/storage/api/entries.clj

https://sentry.io/opencompany/oc-beta-storage/issues/755692215/?referrer=slack

fix for auto share

---

src/oc/storage/async/email.clj

Main PR: https://github.com/open-company/open-company-email/pull/29

Digest tweaks

---

project.clj
src/oc/storage/api/access.clj
src/oc/storage/api/entries.clj
src/oc/storage/resources/board.clj

Main PR: https://github.com/open-company/open-company-email/pull/30

Storage lib

---

project.clj
src/oc/storage/api/entry_point.clj
src/oc/storage/api/orgs.clj
src/oc/storage/representations/entry.clj
src/oc/storage/representations/org.clj

Main PR: https://github.com/open-company/open-company-web/pull/762

Post link behaviour

---

project.clj

Main PR: https://github.com/open-company/open-company-lib/pull/50

Fix decode id-token

---

src/oc/storage/api/entries.clj

Main PR: https://github.com/open-company/open-company-web/pull/766

Check the secure uuid in the token and in the request.

---

README.md
project.clj

Main PR: 
https://github.com/open-company/open-company-lib/pull/51

Use new lib for token verification.

---

project.clj
src/oc/storage/api/access.clj
src/oc/storage/api/boards.clj
src/oc/storage/api/entries.clj
src/oc/storage/representations/org.clj
src/oc/storage/resources/common.clj
src/oc/storage/resources/org.clj

Main PR: https://github.com/open-company/open-company-web/pull/843

Content visibility settings

---

src/oc/storage/config.clj
src/oc/storage/representations/content.clj
src/oc/storage/representations/entry.clj

Main PR: open-company/open-company-web#856
To test backward compatibility:
- clean your DBs
- start storage on this branch
- start web client on `mainline`
- onboard a new org
- add a few posts
- invite and onboard a new user
- make sure the posts are marked as new for the new user
- make sure the posts are marked as read while the user expand or scroll (posts that don't have comments, attachments and small body are marked as read as soon as the user scrolls pass them in the stream)
- make sure the posts are displayed correctly
- edit a post

Mark as unread

---

resources/samples/general.edn
src/oc/storage/representations/entry.clj
src/oc/storage/resources/common.clj
src/oc/storage/resources/entry.clj

Review with https://github.com/open-company/open-company-web/pull/853
NB: this should be backward compatible with the old client so we can go ahead and release it
To test backward compatibility:
- clean out your DBs
- start storage on this branch
- start client on `mainline` (not `carrot-2`)
- onboard Slack
- add a new post
- edit a post
- open a post single page
- open a post with public link
- change to a section
- add a new post
- edit another post
- share

Why it matters

---

project.clj

Card: https://trello.com/c/9m4ZQpnb/2051-wst-updates-backend
Linked PR: https://github.com/open-company/open-company-web/pull/880

WST updates

---

project.clj
src/oc/storage/async/bot.clj

Send to a Slack user via WST send. Does the message come from Carrot bot DM or SlackBot DM?

Honor {:channel {:type ""}} in share-request payload sent from client

---

resources/samples/general.edn
src/oc/storage/api/orgs.clj

This PR just adjust the initial sample post for a new org.
Create a new org, go through NUX, and check the 1 sample post you end up with and verify the above items are true.
- Review code
- Merge (can likely remove `merge-branch`)
- Deploy
- Smoke 'em if you got 'em

Sample post author/comment/reaction

---

src/oc/storage/representations/board.clj

Main PR: https://github.com/open-company/open-company-web/pull/952

Quick post

---

src/oc/storage/api/orgs.clj

Main PR: https://github.com/open-company/open-company-web/pull/969

Fix private WST

---

src/oc/storage/api/activity.clj
src/oc/storage/representations/activity.clj

Review with: https://github.com/open-company/open-company-web/pull/980

Fix Follow-ups pagination

---

src/oc/storage/api/orgs.clj
src/oc/storage/config.clj
src/oc/storage/representations/org.clj

Supports https://github.com/open-company/open-company-web/pull/985

Remove section picker

---

src/oc/storage/config.clj

~Main PR: https://github.com/open-company/open-company-web/pull/988~
Linked PR: https://github.com/open-company/open-company-web/pull/1002

Performance improvement

---

src/oc/storage/api/entries.clj

Bug: right now it's possible to move back a post from published state to draft with a simple PATCH to the entry. Shouldn't be possible.
To test the bug fix:
- edit a published post
- find the PATCH call in the Network tab
- right click on it -> Copy -> Copy cURL
- paste in your editor
- change `"status": "published"` to `"status": "draft"`
- run in terminal
- refresh AP
- post still there?
Regression test:
- create a new post
- add some content
- check autosave works
- refresh page
- add some more
- edit published post
- save

Fix entries status update [WIP]

---

src/oc/storage/api/activity.clj

Bug: right now Digest service is loading the posts using Storage activity API which return the posts paginated. Digest should always get all the posts in one call.
To test:
- try the web client
- now check that digest service is sending digests with at least 8 posts
NB: to test digest you can't use `/_/emai/run` since that uses the JWT in the cookie, you need to use Digest service repl.

Fix digest pagination

---

src/oc/storage/api/entry_point.clj

Trello: https://trello.com/c/2IcGaZ9f/2194-modify-notification-payloads-to-contain-url-to-simplify-mobile-push-notification-tap-handling
Linked PRs:
- Web: https://github.com/open-company/open-company-web/pull/1026
- Mobile: https://github.com/open-company/open-company-mobile/pull/5
- Notify: https://github.com/open-company/open-company-notify/pull/17
To test:
- Follow the test steps in https://github.com/open-company/open-company-web/pull/1026

Expand org publicity check in entry-point to include uuid

---

src/oc/storage/config.clj

Relates to this https://github.com/open-company/open-company-auth/pull/104 but independent.
To test:
- add `export local-dev-host=YOUR_IP_HERE`
- start storage
- check that it listens on your local network ip address instead of localhost

Local config improvements

---

project.clj
src/oc/storage/representations/org.clj
src/oc/storage/resources/common.clj

Main PR: https://github.com/open-company/open-company-web/pull/1120

Sign up refresh

---

src/oc/storage/config.clj
src/oc/storage/representations/org.clj

Main PR: https://github.com/open-company/open-company-web/pull/1125

Reminders feature flag

---

project.clj
src/oc/storage/api/activity.clj
src/oc/storage/api/boards.clj
src/oc/storage/api/orgs.clj
src/oc/storage/db/common.clj
src/oc/storage/db/migrations/1584648489241_add_org_uuid_publisher_index.edn
src/oc/storage/representations/activity.clj
src/oc/storage/representations/entry.clj
src/oc/storage/representations/media_types.clj
src/oc/storage/representations/org.clj
src/oc/storage/resources/entry.clj

Main PR: https://github.com/open-company/open-company-web/pull/1150

People profiles
