open-company/open-company-storage

src/open_company/representations/company.clj
src/open_company/representations/report.clj

https://trello.com/c/n5oBmwg2
To test follow the cURL in the README to create OPEN and BUFFR. Create 2 reports for OPEN and none for BUFFR.
Do a cURL GET on OPEN. See 2 report links in the links? Good.
Do a cURL GET on BUFFR. See no report links in the links? Hot damn.
Merge.

Add HATEOAS links for company reports.

---

README.md
src/open_company/api/companies.clj
src/open_company/api/reports.clj
src/open_company/representations/company.clj
src/open_company/resources/report.clj
test/open_company/integration/company/company_create.clj
test/open_company/integration/company/company_update.clj
test/open_company/integration/report/report_create.clj
test/open_company/integration/report/report_update.clj
test/open_company/lib/hateoas.clj
test/open_company/lib/resources.clj
test/open_company/lib/rest_api_mock.clj
test/open_company/unit/resources/company/company_create.clj
test/open_company/unit/resources/company/company_update.clj

https://trello.com/c/hJ9yLZEC
The responses from a PUT update of a company or a report would still have properties that were removed from the update. This adds failing integration tests for both company and report, and then fixes that so they pass. It also refactors and DRYs the tests some.
The key fixes are in `open-company.api.companies` and `open-company.api.reports`. Study those.
To test:
Note the new integration update tests for report and company. Study them and convince yourself they test the problem. Then run the tests!
```console
lein test!
```
They pass? Shazam!
Still not convinced. Checkout the updated cURL examples in the README. Run those against mainline, see the bug? Now switch back to this branch and run them again. See the fix? Holy boogers, that's good stuff. Merge it.

Fix to PUT response

---

README.md
REPL_notes.clj
api.yml
src/open_company/api/companies.clj
src/open_company/api/reports.clj
src/open_company/representations/company.clj
src/open_company/representations/report.clj
test/open_company/integration/report/report_create.clj

Read all about the various opinions and stances on REST api versioning. Though long and hard about it in my hammock.
Dropped the `/v1/` from the URLs. We'll use versioned subdomains instead. Also updated the versioning on the media-types to be `.v1` rather than `;version=1`. Liberator doesn't handle the  `;version=1` style as it assumes that's a different media-type since multiple media-types are separated by `;` (reasonable assumption really).
Lastly, updated the Reports API to use a `/reports/` in the URL to keep the namespace clean for potential future additions that are quarterly/monthly/yearly.
This updates the API and usage docs (README). 
To test: Read through the usage changes in the README. Changes all make sense? Execute the cURL command sequence in the README, all work? We have …

Update API versioning scheme

---

project.clj
src/open_company/api/companies.clj
src/open_company/config.clj
src/open_company/representations/company.clj
src/open_company/representations/section.clj
src/open_company/resources/common.clj

https://trello.com/c/tm1niuVx
We had a bug last week because the section name in the API internals didn't match the section name of the `sections.json` asset file (fundraising / fund-raising).
DRY'd that up so it won't be possible to have this kind of error. The `sections.json` file now provides the master list of all categories and sections.
To test:
0. Run `lein test!`
1. Run the REPL and try the Clojure code below
2. Look at the code changes
3. Do a few basic actions with the UI
4. Merge
5. Eat some ghost peppers
```clojure
(require '[open-company.resources.common :as common] :reload)
common/categories
(common/sections-for :progress)
(common/category-for :challenges)
common/ordered-sections
common/sections
```

DRY up the section definitions to all be based on the sections.json asset

---

src/open_company/config.clj
src/open_company/db/pool.clj
test/open_company/unit/db/pool.clj

https://trello.com/c/4lF8ifK2
This PR improves the RethinkDB connection pool.
Specifically it throws an exception now if the pool is empty and no connection is available so we'll see this in Sentry. It also fixes a potential problem in the with-connection macro that may have prevented it from recovering properly from a pool empty scenario (it use to try to release nil from the pool).
To test:
0. Review the code
1. Review the new tests, do they test what they claim to? Run them with `lein test!`
2. Decrease the pool size to 2 in `config.clj` and change the log level to `:trace` in `config.clj`
3. Restart your API server, confirm the pool size is 2 in the output
4. Load Buffer in the web app
5. Notice that Buffer loads, but some of the pre-loading of prior sections fail w/ a 500
6. Look at …

Fix some issues with the DB pool

---

src/open_company/api/common.clj
src/open_company/api/companies.clj
src/open_company/api/entry.clj
src/open_company/api/sections.clj

This PR makes use of Liberators `:initialize-context` step for reading and decoding the `jwtoken` if present. If an invalid token is supplied `{:jwtoken false}` is merged into `ctx`.
By separating parsing/decoding of `jwtoken` from actual authentication the  `allow-anonymous` and `allow-org-members` checks became trivial removing the need for separate `authenticated?` and `authorized?` functions.
I tested this mostly by just running the test suite, I think since they cover the basic token situations at least once that should probably be enough. Also did a bit of `curl` testing and it's all working well.

refactor token handling + allow-anon

---

src/open_company/config.clj
src/open_company/db/pool.clj

https://trello.com/c/scAtiIZc
Implement @martinklepsch suggestion of limiting pool size to core.async limits (for now, until driver is fixed). 
Also fixes the bug of a race condition starting the DB pool which often results in multiple pools from a cold start and the dreaded DB thread lockup of death problem.
To test:
0- Review the code
1- Set your logging level to `trace` in config.clj
2- Calculate: (your machine's cores * 2) + 21
2- Start the API server and note the DB Pool size output, does it match your calculation?
3- Hit your cold API server with your warm web app (just cmd-R a local OC web page), this should result in multiple API requests in very close proximity
4- No lockup?
5- Look at your `/tmp/oc-api.log` file, it has just one of each of these, not 2 like this?
```
16-02-24 …
```

Derive the default DB pool size from core async thread limits.

---

src/open_company/app.clj
src/open_company/db/pool.clj
src/open_company/resources/common.clj
src/open_company/util/sample_data.clj
test/open_company/lib/db.clj
test/open_company/unit/db/pool.clj
test/open_company/unit/resources/common.clj

This replaces the existing connection pooling implementation with one that is capable of invalidating connections.
Also using `open-company.db.pool/rebuild-pool!` it is now possible to rebuild the pool in the case RethinkDB has been restarted or similar.
- Run tests
- Review changes in inidividual files
- Review `default-timeout` (300ms)
Addressing the individual points from the [trello card](https://trello.com/c/5ebQjwZS/208-db-pool-improvements):
---
**return other than :ok for start if it fails to start**
A pool can always be started. If the pool fails to create a resource it will try again in a specified interval (default: 5s). If the pool continously fails to create resources any attempts to claim a resource from the pool will throw an exception.
---
**check for validity of …

Connection Pooling w/ invalidation & with-timeout macro

---

README.md
REPL_notes.clj
opt/samples/bago.edn
opt/samples/buffer.edn
opt/samples/pied-piper.edn
project.clj
src/open_company/api/companies.clj
src/open_company/api/sections.clj
src/open_company/assets/sections.json
src/open_company/representations/section.clj
src/open_company/resources/common.clj
src/open_company/resources/company.clj
src/open_company/resources/section.clj
test/open_company/integration/company/company_create.clj
test/open_company/integration/company/company_retrieval.clj
test/open_company/integration/section/section_manipulation.clj
test/open_company/integration/section/section_revision.clj
test/open_company/unit/resources/company/company_create.clj
test/open_company/unit/resources/company/company_manipulate.clj

Trello: https://trello.com/c/AWy33aAt
This PR fixes a hodgepodge of minor API issues:
* Defaults all section headlines to blanks
* Makes image and description read only properties of sections
* Remove PUT from company
* Makes PATCHed sections w/ no content get created as placeholders
* Disallow PATCHing made up sections into company
* normalize s/ as namespace alias for string and schema/ for prismatic schema
* Update icon set (also move it to S3 for easier updating w/o code changes)
* Ensures HATEOAS modify links are only present on individual section retrieval when they should be
* Ensures all the usage documented in the README works
To test:
* Look most closely at the test updates in the code changes. Ensure the tests are passing
* Observe the current new topic creation behavior in the …

Minor API changes

---

README.md
project.clj
src/open_company/api/common.clj
src/open_company/api/companies.clj
src/open_company/api/entry.clj
src/open_company/api/sections.clj
src/open_company/app.clj
src/open_company/components.clj
src/open_company/db/pool.clj
src/open_company/representations/company.clj
src/open_company/representations/section.clj
src/open_company/resources/common.clj
src/open_company/resources/company.clj
src/open_company/resources/section.clj
src/open_company/util/sample_data.clj
src/user.clj
test/open_company/integration/company/company_create.clj
test/open_company/integration/company/company_list.clj
test/open_company/integration/company/company_retrieval.clj
test/open_company/integration/entry.clj
test/open_company/integration/section/section_manipulation.clj
test/open_company/integration/section/section_new.clj
test/open_company/integration/section/section_revision.clj
test/open_company/lib/db.clj
test/open_company/lib/rest_api_mock.clj
test/open_company/lib/test_setup.clj
test/open_company/unit/resources/company/company_create.clj
test/open_company/unit/resources/company/company_list.clj
test/open_company/unit/resources/company/company_manipulate.clj
test/open_company/unit/resources/section/section_revision.clj

trello card: https://trello.com/c/ixDW0KE3/47-switch-config-startup-shutdown-to-component
This PR refactors all code to have state passed explicitly, utilizing the component library to build/destroy this state.
Doing this refactoring it became painfully apparent how global state was spread over this codebase. In some places a database connection needs to be passed down very far. Ultimately this code should be refactored to get the required DB-originating data earlier in the callstack but I think that's outside of the  scope of this PR.
Also there's very pervasive usage of `with-pool` in all the api namespaces which kind of sucks but I haven't yet found a way to wrap liberators `defresource` in something like `with-pool`. If you have an idea, let me know.
To test I think tests should cover …

Componentize

---

src/open_company/api/entry.clj
src/open_company/components.clj

trello card: https://trello.com/c/hO9YdZCn/391-db-pool-output
**To test:** Deploy/run locally and verify there are no messages like these printed
```
#object[clojure.lang.Atom 0x6ad5e42 {:status :ready, :val {:client << stream: {:type "splice", :sink {:type "netty", :closed? false, :sink? true, :connection {:local-address "/127.0.0.1:62120", :remote-address "localhost/127.0.0.1:28015", :writable? true, :readable? true, :closed? false, :direction :outbound}}, :source {:pending-puts 0, :drained? false, :buffer-size 0, :permanent? false, :type "netty", :sink? true, :closed? false, :pending-takes 1, :buffer-capacity 0, :connection {:local-address "/127.0.0.1:62120", :remote-address "localhost/127.0.0.1:28015", :writable? true, :readable? true, :closed? false, :direction :inbound}, :direction …
```

remove printing of connection object

---

opt/samples/buffer.edn
src/open_company/assets/sections.json
src/open_company/resources/company.clj

https://trello.com/c/ro7Miff6
Review with https://github.com/open-company/open-company-web/pull/105
To test:

Update handling of Growth placeholder section

---

README.md
REPL_notes.clj
docs/stakeholder-updates.md
opt/samples/bago.edn
opt/samples/blank.edn
opt/samples/buffer.edn
opt/samples/ent.edn
opt/samples/new.edn
opt/samples/pied-piper.edn
opt/samples/read-only.edn
opt/samples/simple.edn
opt/samples/uni.edn
opt/samples/yoyo.edn
src/open_company/api/stakeholder_updates.clj
src/open_company/assets/sections.json
src/open_company/representations/stakeholder_update.clj
src/open_company/resources/common.clj
src/open_company/resources/stakeholder_update.clj
src/open_company/util/sample_data.clj
test/open_company/integration/company/company_retrieval.clj
test/open_company/integration/section/section_manipulation.clj
test/open_company/unit/resources/company/company_create.clj
test/open_company/unit/resources/company/company_manipulate.clj

https://trello.com/c/7kDEhTVe
This PR:
* removes the "financial" category
* removes the data privacy section
* moves sections into the 2 remaining categories
* updates tests to reflect the above changes
* updates README to reflect the above changes
* Moves the help and kudos sections
* Removes outro/intro from SUs
This has been deployed to staging already and the sample data there has been updated. To test:
Review the code.
Tests passing?
README REPL and cURL code works?
Look at the JSON company responses for a few companies on staging. No financial category? Dashboard and add topics still work OK? No data privacy section in add topics? No intro/outro in SU?
List SU's for Buffer with a GET (cURL). No intros? GET a specific SU with it's link. No intros/outros in either?
To deploy to prod: …

Category / SU update

---

src/open_company/api/stakeholder_updates.clj
src/open_company/resources/stakeholder_update.clj

https://trello.com/c/7XF15qY8
Add location header in response when SU is created via POST.
To test:
Before this (on mainline) run:
```
curl --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyLWlkIjoic2xhY2s6VTA2U0JUWEpSIiwibmFtZSI6IlNlYW4gSm9obnNvbiIsInJlYWwtbmFtZSI6IlNlYW4gSm9obnNvbiIsImF2YXRhciI6Imh0dHBzOlwvXC9zZWN1cmUuZ3JhdmF0YXIuY29tXC9hdmF0YXJcL2Y1YjhmYzFhZmZhMjY2YzgwNzIwNjhmODExZjYzZTA0LmpwZz9zPTE5MiZkPWh0dHBzJTNBJTJGJTJGc2xhY2suZ2xvYmFsLnNzbC5mYXN0bHkubmV0JTJGN2ZhOSUyRmltZyUyRmF2YXRhcnMlMkZhdmFfMDAyMC0xOTIucG5nIiwiZW1haWwiOiJzZWFuQG9wZW5jb21wYW55LmNvbSIsIm93bmVyIjpmYWxzZSwiYWRtaW4iOnRydWUsIm9yZy1pZCI6InNsYWNrOlQwNlNCTUg2MCJ9.9Q8GNBojQ_xXT0lMtKve4fb5Pdh260oc2aUc-wP8dus" -X POST -i http://localhost:3000/companies/buffer/updates | grep Location
```
Notice the …

Include location in response to snapshot creation.

---

src/open_company/representations/company.clj
src/open_company/resources/common.clj
src/open_company/resources/company.clj
test/open_company/integration/section/section_manipulation.clj
test/open_company/unit/resources/common.clj

https://trello.com/c/2rlA4fLv
This test fixes a bug where re-adding an archived section causes the oldest section to be added back. It also adds an `archived` key to company containing all the company's archived sections (names and titles).
To test the bug fix:
* Start w/ a cleanly imported Buffer **ON MAINLINE**
* Archive "Team and Hiring"
* Add "team" topic back in, look at the content, notice it's now showing the oldest content, (July 13, 2015), not the latest content, this is bad.
* Now switch to this branch and start again w/ a cleanly imported Buffer
* Archive "Team and Hiring"
* Add "team" topic back in, look at the content, notice it's now showing the newest content, (November 20, 2015), this is good.
To test the `archived` key:
* Start w/ a cleanly imported Buffer on this branch …

Return :archived topics in company responses. And archiving bug fix.

---

docs/stakeholder-updates.md
project.clj
src/open_company/api/stakeholder_updates.clj
src/open_company/resources/stakeholder_update.clj

https://trello.com/c/Tp81KgiO
Fixes bug: can't directly assoc on the liberator request context when using nginx-clojure. Need to update it indirectly by returning a map that liberator merges in itself (this is the right way to do it anyway). Also a bit more cleanup removing intro/outro.
To test:
* Run API on this branch
* Create a snapshot with the web UI
* Share the URL. Does the POST work or does it 500? Works? About damn time.
* Merge
* Deploy
* Sing the hits of Neil Diamond

Snapshot POST bug on staging/prod

---

opt/samples/bago.edn
project.clj
src/open_company/api/sections.clj
src/open_company/assets/sections.json
src/open_company/resources/common.clj
src/open_company/resources/company.clj
src/open_company/resources/section.clj
test/open_company/integration/company/company_create.clj
test/open_company/integration/company/company_retrieval.clj
test/open_company/integration/section/section_manipulation.clj
test/open_company/integration/section/section_revision.clj
test/open_company/lib/resources.clj

https://trello.com/c/1CaoeZfD
This PR adds the ability for the API to work with custom topics, in addition to the ones we already know about. It also removes the section `icon` property which is no longer used.
To test:
```
curl --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyLWlkIjoic2xhY2s6VTA2U0JUWEpSIiwibmFtZSI6IlNlYW4gSm9obnNvbiIsInJlYWwtbmFtZSI6IlNlYW4gSm9obnNvbiIsImF2YXRhciI6Imh0dHBzOlwvXC9zZWN1cmUuZ3JhdmF0YXIuY29tXC9hdmF0YXJcL2Y1YjhmYzFhZmZhMjY2YzgwNzIwNjhmODExZjYzZTA0LmpwZz9zPTE5MiZkPWh0dHBzJTNBJTJGJTJGc2xhY2suZ2xvYmFsLnNzbC5mYXN0bHkubmV0JTJGN2ZhOSUyRmltZyUyRmF2YXRhcnMlMkZhdmFfMDAyMC0xOTIucG5nIiwiZW1haWwiOiJzZWFuQG9wZW5jb21wYW55LmNvbSIsIm93bmVyIjpmYWxzZSwiYWRtaW4iOnRydWUsIm9yZy1pZCI6InNsYWNrOlQwNlNCTUg2MCJ9.9Q8GNBojQ_xXT0lMtKve4fb5Pdh260oc2aUc-wP8dus" …
```

Custom topic support

---

src/open_company/lib/bot.clj

[trello card](https://trello.com/c/QTeRaScu/495-update-onboarding-script-to-update-logo-rather-than-name)
This is not actually required in 99% of the cases (companies usually don't have a logo when they onboard) but since the bot now does things with the logo it seems relevant enough to be included in the message.
No real test steps as well

Send logo as script param if present

---

opt/samples/buffer.edn
project.clj
src/open_company/api/companies.clj
src/open_company/assets/sections.json
test/open_company/integration/company/company_list.clj
test/open_company/lib/resources.clj

Fix for: https://trello.com/c/K7JydNen
Base cause of this is RethinkDB skips documents w/o specified properties in retrieval, and logo was a specified property, but logo isn't added to the document until later by the bot (which might not finish).
To test:
To review:
Deployment:
Current API branch for both staging and beta is called `email-snapshot`. So...

Companies w/ no logo are not in the company list

---

opt/samples/18F.edn
opt/samples/buff.edn
opt/samples/green-labs.edn
opt/samples/simple.edn
project.clj
src/open_company/api/stakeholder_updates.clj
src/open_company/assets/migration.template.edn
src/open_company/assets/sections.json
src/open_company/db/migrations/1477574597620_add_update_medium.edn
src/open_company/representations/company.clj
src/open_company/representations/section.clj
src/open_company/representations/stakeholder_update.clj
src/open_company/resources/common.clj
src/open_company/resources/section.clj
src/open_company/resources/stakeholder_update.clj
test/open_company/integration/stakeholder_update/stakeholder_update_create.clj
test/open_company/lib/check.clj
test/open_company/lib/resources.clj
test/open_company/lib/rest_api_mock.clj
test/open_company/unit/resources/stakeholder_update/distinct_updates.clj

This API change supports showing prior updates in the UI.
The main change of this PR is to implement a heuristic by which we don't return every 
This PR also has us keeping the share details that get passed on to the email/bot services with the update so we have data on how the update was shared.
It also updates the default "growth" title to be "Key Metrics".
To test:
* Review the code
* Review the new tests in `distinct_updates.clj`. Do they test the new heuristic?
* Look at prior updates in the web UI, does it work? Does it implement the heuristic in your testing?
* Merge
* Review the UI PR
* Deploy them to beta
* Dance, dance, dance

Prior Updates

---

README.md
project.clj
src/open_company/resources/stakeholder_update.clj
test/open_company/unit/resources/stakeholder_update/distinct_updates.clj

https://trello.com/c/JctchmaC
Requires this UI PR: https://github.com/open-company/open-company-web/pull/209
This PR removes share medium as a cause of distinction in prior updates, and instead has collapsed updates accumulate all the ways they've been shared, so that medium in the returned update may be sequential.
To test:
* Review the code of both PRs
* Review the updated tests of this PR. Do they pass? Do they cover collapsing medium scenarios?
* Test in the UI by looking at the update list of some existing companies you have, Buffer, etc. Nothing broken?
* Create a new update with a new title
* Share it as a link, check the update list, has link as medium?
* Share it (don't change the title) by email, check the update list, has link and email?
* Share it (don't change the title) by …

Update code and tests for collapsing distinct mediums

---

src/oc/storage/api/access.clj
src/oc/storage/config.clj
src/oc/storage/representations/board.clj
src/oc/storage/representations/entry.clj

Supports PR: https://github.com/open-company/open-company-interaction/pull/2
To test, look at board JSON responses. Do they contain a unique websocket URL for each board if the user is an author or a viewer? Is it the correct URL? 
Is the URL not there for public and/or anonymous access?
Groovy. Merge this bad boy.

Include interaction websocket link in board responses.

---

README.md
REPL_notes.clj
project.clj
src/oc/storage/api/boards.clj
src/oc/storage/api/entries.clj
src/oc/storage/async/change.clj
src/oc/storage/representations/org.clj

https://trello.com/c/Um6p3FXO
This PR supports [https://github.com/open-company/open-company-web/pull/270](https://github.com/open-company/open-company-web/pull/270).
This updates the SQS triggers sent to change service to have 3 event types: `add`, `refresh`, and `delete` and 2 content types: `board` and `entry` to account for the 6 changes we need to report to the UI:
- board add
- board update
- board delete
- entry add
- entry update
- entry delete
This also puts those triggers in the right place in the API so the SQS events go out for all 6 of the above.

Change events

---

README.md
project.clj
src/oc/storage/app.clj
src/oc/storage/config.clj
src/oc/storage/representations/org.clj

https://trello.com/c/LWg96uIO
To test this PR:

Carrot-powered What's New Content

---

src/oc/storage/async/notification.clj
src/oc/storage/representations/entry.clj

No trello card for this.
In the spirit of small commits!
This is a small fix and a refactor.
The fix is to not include the `reactions` key in entry responses (on their own and embedded in a board).
To test the change, look at board and entry responses (web developer console, or cURL or Paw) as on public content as anonymous (no JWT, or JWT for wrong org) and on content as a team user. You should see no `reactions` key no for the former, rather than a empty `reactions` key. You should still see `reactions` for team members.

Small fix & refactor

---

src/oc/storage/util/search.clj

https://trello.com/c/vKVYCYMZ
This change uses `list-entries-by-board` so you don't hit the limit used in `list-entries-by-org`.

Fix for not querying all entries.

---

src/oc/storage/util/search.clj

The board's authors and viewers are needed for the search index.

missing data needed for filtering out private entries.

---

src/dev.clj
src/oc/storage/async/notification.clj
src/oc/storage/components.clj

No Trello card.
Just cleans up our use of the core.async producer/consumer pattern we have throughout many of the services with a parked, rather than a blocked read.
Also discourages use of `(start)` at the REPL and improves component life-cycle logging.
To test:

Async pattern

---

project.clj
src/oc/storage/api/activity.clj
src/oc/storage/api/boards.clj
src/oc/storage/api/entries.clj
src/oc/storage/config.clj
src/oc/storage/representations/activity.clj
src/oc/storage/resources/reaction.clj

https://trello.com/c/mOvOdYTQ
This PR removes server-side user and org favorite reactions. We're now relying on just the recent used stuff from emoji mart.
To test:

Remove user and org favorite reactions.

---

src/oc/storage/api/boards.clj
src/oc/storage/async/notification.clj
src/oc/storage/resources/common.clj

Send board notifications over SNS so the bot and email service can notify users of changes.
See testing instructions:
https://github.com/open-company/open-company-auth/pull/28

Send user data with board changes.

---

src/oc/storage/api/entries.clj
src/oc/storage/representations/entry.clj
src/oc/storage/resources/common.clj
src/oc/storage/resources/entry.clj

https://trello.com/c/kjfhXr7U
This is to support a Web PR that doesn't exist yet, which pulls attachments out of the body prop and into their own sequence like we've had them before.
Review with [Web/attachments#396](https://github.com/open-company/open-company-web/pull/396)
Test with the new Web work when it's ready:

Return of the Attachments.

---

src/oc/storage/api/boards.clj
src/oc/storage/resources/entry.clj

This will allow a user to move an existing entry to a newly created board.

upsert entry support when creating a new board.

---

src/oc/storage/api/entries.clj

This change adds back the auto share to slack on publish.
To test:
- create  a section that auto shares to slack
- create a post and save it as a draft
- edit the draft and post it
- create a post and post instead of saving as draft

add back the auto share on publish after publishing a draft.

---

src/oc/storage/api/boards.clj

Bug:
- click Compose
- click on the current section name
- click Add a new section
- add a new section name
- click Create
- add the post title
- add the post body
- click Post
- error!
The notification trigger was still using the old form w/o the note at the end so it was creating an erroneous payload for the notification.
To test:
- repeat the test above with this branch
- now repeat it but select private board and add another user and a personal note

BUGFIX: create a new post within a new section doesn't work

---

src/oc/storage/resources/common.clj

Right now the file-type property of post attachments is required to be not empty. It's possible that Filestack return an empty file-type when used to upload a file.
To test:
- create a new post
- add an attachment
- select clojure file (with .clj extention)
- filestack should upload it and read it with empty file type
- save the post
- go back to the board or AP
- check the board/AP refresh

Optional file type for attachments

---

src/oc/storage/api/entries.clj

This change uses the updated section information for a post.
To test:
- Without the fix create a draft using a section with slack mirroring.
-  Publish the draft after changing to a section without slack mirroring.
- With the fix create a draft using a section with slack mirroring.
- Publish the draft after changing to a section  without slack mirroring.

Use the correct section info when changing section for a post on publish.

---

resources/default-new-org.edn

No Trello card.
This is a simple, pro-active change to avoid potential problems down the road with the sample post user-ids (publisher, commenter, and reacter) not being unique, and being the same as the draft board UUID (`0000-0000-0000`).
Needs to go out with the web branch of the same name that looks for the sample post as one by `1111-1111-1111` rather than `0000-0000-0000`.
Web PR: https://github.com/open-company/open-company-web/pull/568

Unique IDs for sample post users

---

src/oc/storage/api/entries.clj

On most entry updates the key `:moving-board` is going to be empty since the user didn't move the board.
I made sure that the `moving-board` is retrieved out of the `if-let` so the entry update won't fail.
Slack: https://sentry.io/opencompany/oc-staging-storage/issues/593780255/?referrer=slack
I'm not sure how to test this, the best thing would be to send a PATCH request for an entry w/o a board-slug specified in the entry map, this shouldn't trigger an error.

Fix moving board

---

project.clj
src/oc/storage/api/boards.clj

Bug: with incognito visit a public board, do you not see it? Not good.
Fix: avoid requiring a user to retrieve a board.
To test:
- login
- go to a board
- set it to be public
- now refresh
- create a draft
- visit the draft board
- copy the public board url
- logout
- visit the public board
- now visit a team or public board

Bugfix: public boards are not visible to anonymous users

---

LICENSE
README.md
project.clj
src/oc/storage/db/migrations/1534797688142_entry_versions.edn
src/oc/storage/representations/entry.clj
src/oc/storage/resources/common.clj
src/oc/storage/resources/entry.clj

First pass at versioning entries (aka posts). 
This change creates a new table `versions_entries` that will keep track of each version. A version is created on each entry change (create, edit, publish, and delete).  The contents of the entry is saved in the version table along with `:revision-id` `:version-uuid` `:revision-date` and `:revision-author`. `:revision-id` is also added to entry so that you know what the current version is.
The first version doesn't have an entry in the versions table, but does have a `:revision-id` equal to 0.
To test this you will need to be able to list all the items in the `entries` and `versions_entries` table.
I used http://localhost:8080/#dataexplorer to list the data.
Test steps:
- migrate your local DB
- create a post in the web ui as a draft
- from …

Post versions

---

.travis.yml
project.clj
src/oc/storage/api/orgs.clj
src/oc/storage/async/notification.clj

Supports: https://github.com/belucid/open_company_activity_notifier/pull/1
Made the note optional in the notification (should have always been) since this new `:nux` notice doesn't have a note.
Testing:
This is on staging (for regression only). Can't NUX a user on staging and see this cause we don't run activity monitor there.
For the positive test you can get activity monitor running locally and NUX a user and see if it reports the sections selected. Or you can just look at #test-channel where I did the same.
Mainly looking for a regression here... so do some basic regression testing on the things that depend on storage SNS notifications and make sure none of them are broken:

SNS notification of NUX board selection.

---

src/oc/storage/api/boards.clj

Allow the pre-flight board name check to pass if the proposed name slugifies into any name in the exclude sequence passed in to the pre-flight check.
To test: refer to the [web PR](https://github.com/open-company/open-company-web/pull/632).

Pre-flight check update

---

project.clj
src/oc/storage/api/orgs.clj

This fixes an issue creating drafts when inviting users w/o a People section.
To test:
- Sign up with a new org
- UNSELECT People as a "Topic that Matters"
- Delete your pre-existing draft
-  Now, create a post in section "People" and publish it
- Merge
- Deploy to beta
- Thank your lucky stars

People invite broken

---

src/oc/storage/api/boards.clj

The auto save feature needs to have access to the newly created post when it uses the new board api to create the post.  This change returns the entries belonging to the board/section.

Return new entries on board creation.

---

src/oc/storage/api/boards.clj

When creating a board we don't want to return all the drafts.  We only want to return the entries for the specified board.
To test:
- create a few drafts with existing boards
- open cmail
- add a new section with the section picker
- wait for the autosave

Filter by board uuid to only return entries for the board created.

---

project.clj
src/oc/storage/api/orgs.clj

No Trello card.
This addresses 1 of the 4 search cases that failed in today's testing. Namely the case of not finding the user's auto-created draft in search results.
To test:

Notify SNS of initial draft for users.

---

src/oc/storage/api/entries.clj
src/oc/storage/resources/entry.clj
src/oc/storage/util/ziggeo.clj

If an error is returned from the Ziggeo API call, mark the entry appropriately. 
This one is tough to test since we don't currently display any error conditions.  Also you have to manually code in the error from the API call to test. 
To test:
- make sure video works normally
- change the API call to `if` instead of `if-not` https://github.com/open-company/open-company-storage/blob/ziggeo-api-error/src/oc/storage/api/entries.clj#L58

Ziggeo api error

---

project.clj
resources/samples/all-hands.edn
resources/samples/decisions.edn
resources/samples/design.edn
resources/samples/general.edn
resources/samples/lessons-learned.edn
resources/samples/marketing.edn
resources/samples/people.edn
resources/samples/product-updates.edn
resources/samples/week-in-review.edn
src/oc/storage/api/orgs.clj
src/oc/storage/async/bot.clj
src/oc/storage/config.clj

https://trello.com/c/o1nxc6hg
This PR:
- swaps out the main "General" samples for one with the Carrot video embedded in it
- adds 2 additional "General" section samples if needed
- ensures there are a minimum of 3 sample entries w/ every NUX
- ensures there are a maximum of 4 sample entries w/ every NUX
To test, go through NUX 3 times...
Minimal:
- NUX a new org, and when selecting topics, deselect EVERY topic
Usual path:
- NUX a new org, and when selecting topics, don't do anything, leave the defaults as-is
Maximal:
- NUX a new org, and when selecting topics, select EVERY topic

NUX video post and min/max sample entries

---

src/oc/storage/api/orgs.clj

BUG: sample posts are not created right now on staging but they are locally. Problem is that we are passing board names to `oc.storage.api.orgs/default-entries-for` function instead of slugs.
Since MacOS is not case sensitive for filenames it works locally when the section name is equal to the slug (ie no spaces but dash like All-hands, for Team and Hiring it won't work).
On staging no sample posts are created since it's also case sensitive.
NB: tests needs to be run on staging
To test:
- deploy mainline to staging
- create a new org
- select ONLY the following sections: Product updates and Week in review
- deploy this branch to staging
- create a new org
- select ONLY the following sections: Product updates and Week in review

Fix sample posts retrieve.

---

project.clj
src/dev.clj
src/oc/storage/components.clj

No trello card.
Sometimes we need to be able to run the REPL for only DB access w/o running all the other components in the service. This PR makes it easy with `(go-db)`.
To test:
- Launch a REPL
- Run `(go-db)`
- Access DB with `(team/list-teams conn)`
- Stop with `(stop)`
- Regression test with `(go)`
- Stop with `(stop)`
- Merge

Allow us to easily use the REPL for DB access only

---

src/oc/storage/resources/org.clj

Ensure that the org slug doesn't go over the 127 rethinkdb, char limit for primary keys.
To test
- sign up and when you create an org use a really long name (over 127 chars)

Truncate org slug

---

project.clj
src/oc/storage/config.clj

https://trello.com/c/i6ysX5UJ
This merely adjust the sections in NUX.
To test:
-  NUX a new org.
- Merge
- Deploy
- Repeat

Adjust default and available NUX boards.

---

src/oc/storage/api/entries.clj
src/oc/storage/resources/entry.clj

We skip the creation of a new post version when sharing a post.
Right now we get an error if we share the same post more than once. The error is from rethinkdb (duplicate primary key). 
https://sentry.io/opencompany/oc-beta-storage/issues/742781328/?referrer=slack
This will be difficult to test once we fix the rage click on the share button.
To test for now:
- share a post

No version update when sharing a post

---

project.clj
src/oc/storage/api/activity.clj
src/oc/storage/api/boards.clj
src/oc/storage/api/entries.clj
src/oc/storage/api/orgs.clj

Proposed solution for the duplicated `:shared` key, the problem is that Liberator apply a deep merge/concat function on the keys of the context between handlers.
The solutions i have thought are 2:
1) avoid reusing the same key
2) use a meta key `:replace` on the data to make sure Liberator replace them
The former can be tricky and can lead to bugs if you forget or with new devs, so i went for the latter, here is the solution i propose.
If you like it we should apply the same set of changes to auth (i don't think we have other services that writes to RethinkDB).
To discuss: how much do you think would be a good limit for `:author` and what data should we keep? For example should we keep only the last x authors or the last x not equal authors (compact continuous edits from the same author …

Fix duplicated share [WIP]

---

src/oc/storage/api/entries.clj

Reverse the order of the shared list to keep the most recent ones.
To test:
- take an entry with 50 shares
- add another

Fix shared limit

---

src/oc/storage/api/boards.clj
src/oc/storage/api/entries.clj

I checked again all the places where i added `api-common/rep` to avoid deep merging/concat of Liberator context, here is a couple of places i think i used it in the wrong way.
To test:
- signup
- create a new board
- change board settings to public
- change board settings to private
- add people to the board

Better use of `api-common/rep`

---

project.clj
src/oc/storage/resources/maintenance.clj

Add a script that:
- load all the orgs in batches (batch size and index are input parameter)
- for each org load all the published entries
- for each entry that has more than 1 share
- group the shares by shared-at
- get only one value for each of them (the rest are duplicates)
- sort the remaining by reverse shared-at
- keep only the most recent 50 items
Let me know if you think this can work, i'll run a test on staging as first thing
To test:
- open your local `lein repl`
- `(go-db)`
- `(maint/shared-limit! conn {:batch-length 10 :batch-offset 0 :dry-run true)` (10 is the number of orgs per batch, 0 is the index of the batch)
NB: i ran this on staging and cleaned all the orgs, the one that had real problems was 18f, one entry had 65535 shares so it was timing out the DB when loaded, now …

Cut shared lists

---

project.clj
resources/samples/drafts.edn
src/oc/storage/api/orgs.clj
src/oc/storage/config.clj

https://trello.com/c/MXle3ZKn
Requires https://github.com/open-company/open-company-web/pull/738
This PR and the Web PR remove the NUX draft post for new users.
To test:
- Create a new org via Slack
- Create a new org via email
- Invite a contributor to the org
- Sign-in with the invited contributor
- Merge both
- Deploy both
- Take a shot of whiskey (deploy drinking game)

Remove initial NUX draft post. Wasn't getting used.

---

src/oc/storage/async/notification.clj
src/oc/storage/config.clj
src/oc/storage/util/search.clj

Needed: https://github.com/open-company/open-company-lib/pull/52
This change writes to a kinesis firehouse if an exception is thrown using SNS.  This is to help get around the limitations of SNS (size, 256kb limit, is the main concern here.)
Each service interested in the notification data from storage will have to use the new function provided in open-company-lib.
Service PRS:
https://github.com/open-company/open-company-notify/pull/7
https://github.com/open-company/open-company-change/pull/13
https://github.com/open-company/open-company-email/pull/40/
https://github.com/open-company/open-company-bot/pull/53
https://github.com/open-company/open-company-search/pull/13
Deploy with https://github.com/belucid/open-company-infrastructure/pull/96
To test:
- create a long post ~260k characters …

Kinesis s3 sns.

---

project.clj
src/oc/storage/resources/org.clj

To test:
- Have on org w/ at least 1 reminder
- See the reminder at the Reminder REPL with `(reminder/list-reminders conn "<ORG UUID")`
- Delete the org at the Storage REPL with `(org/delete-org! conn "<ORG SLUG>")`
- Merge
- Shake it like a Polaroid picture

Cleanup reminders when orgs get removed.

---

src/oc/storage/api/boards.clj

Bug:
- open Cmail
- enter title
- enter body
- wait for autosave to finish
- click on section
- click new section
- enter name of section and wait for preflight to complete
- now quickly save the new section and publish the entry right away
with the bug still in place you should get to a situation like the one below with a post that doesn't appear in AP because it's missing `:publisher` and `:published-at` even if the status is `published`.
Notice the author is missing in the image
Now repeat the test with this fix and check that the newly created post has an author and appears in AP.

Bug on publishing

---

project.clj
src/oc/storage/representations/entry.clj

Review with https://github.com/open-company/open-company-slack-router/pull/14
@belucid i assigned this to you since i am not sure this change has implications with security. Before we were adding the board-slug only if the post was loaded via the secure uuid and `board-slug` and `board-name` only if it was still a draft. I don't see a problem in always returning `board-slug` and `board-name` but i may be wrong.

Slack unfurl updates

---

project.clj
src/oc/storage/api/entries.clj
src/oc/storage/async/bot.clj

Bug: if you have a section set to autoshare to Slack but then remove the bot or the Slack org  we still try to publish. It can work if the user still has the bot stuff in the JWT but if not it was breaking the publish action.
To test:
- signup with a new Slack org (remove it from your DB if you need to)
- add the bot
- add a section with auto share to a slack channel
- now go to settings and remove the slack org completely
- without refreshing and logging out or in go to that sectiona again
- publish a post to that section
- now logout and back in (or `OCWebForceRefreshToken()` in console)
- publish a post to the same section

Fix autoshare error

---

src/oc/storage/api/boards.clj

Bug: sometimes the reactions are returned in plain list from storage not grouped by emoji. The client is not always showing them that way since it depends if a certain post was loaded from the activity or the board API for last (we keep only one version of each post in the web client so the last loaded remains).
To test:
- with mainline
- with user 1 go to AP
- add a post to board A
- add a reaction with user 1
- add the same reaction and another with user 2
- now with user 1 nav to board A (from AP)
- you should see 3 reactions instead of 2 and w/o a count besides it
- now switch to this branch
- go to AP
- refresh
- nav to board A
- 💥

Fix reactions count

---

project.clj
src/oc/storage/config.clj
src/oc/storage/resources/entry.clj

Bug: right now storage doesn't send the `parent-uuid` properties with the list of comments when they are included in the entry. To test this:
- go to an entry
- add a few replies to different comments
- stop interaction service
- refresh the page
-  💥 all comments are shown as root comments
Fix: this simply make sure the parent-uuid is included in the comments.
To test:
- repeat the test steps above and make sure the comments are threaded as they should be
NB: can be that you don't see all the comments when refreshing the post with IS down, that's because storage only sends the first 10 comments with each entry and a total count.

Fix comment threads

---

project.clj
src/oc/storage/lib/sort.clj
src/oc/storage/representations/entry.clj

Card: https://trello.com/c/5dfbiYTG
To test:
- user A go to AP in recent activity sort
- user B go to AP in recent activity sort
- add post A with user A
- add post B with user B
- add a comment with user A on post B
- add a comment with user A on post A
- add a comment with user B on post A
- add a comment with user B on post B
NB: NEW badge is important to check. In the sort we still need to exclude the current user comments when looking for the max comment created-at. This is because when a user expand a post it marks it as read but then a comment is added so the new comment timestamp will result as added after the read and the UI will show the NEW badge.

Recent activity sort fix

---

src/oc/storage/api/boards.clj
src/oc/storage/db/common.clj
src/oc/storage/representations/board.clj
src/oc/storage/urls/board.clj

Bug: pagination on boards is broken because they are missing the direction parameter and also the start parameter is not passed in properly.
To test:
- test pagination on an arbitrary board
- test drafts board with less than 10 posts
- test drafts board with more than 10 posts
- test pagination in AP
- test pagination in Follow Ups
- every other test you can thing around board representation and pagination
- check reactions are aggregated properly in boards
- check reactions are aggregated properly in AP/Unread/Bookmarks
- check first 10 comments are returned properly from board endpoint
- check first 10 comments are returned properly from AP/Unread/Bookmarks endpoint

Fix boards pagination

---

src/oc/storage/api/boards.clj
src/oc/storage/representations/board.clj
src/oc/storage/representations/entry.clj

Recent changes to query and board pagination broken drafts board. Now all the unpublished posts have "drafts" as board slug in the urls. So operations like DELETE fails.
To test:
- try to create a new draft
- try to edit it
- try to delete it
- create another
- edit it
- publish it
- make sure it's published (regression)
- try to edit the published post (regression)
- try to delete the published post (regression)
- test pagination on a normal board (regression)
- test pagination on AP
- test drafts board with more than 10 posts (no pagination)

Fix 404 on drafts entries

---

.gitignore
src/oc/storage/api/activity.clj
src/oc/storage/api/boards.clj
src/oc/storage/representations/activity.clj
src/oc/storage/representations/board.clj

Bug: board creation is currently broken.
Since single query PR went on we have had problems in the board endpoint. The problem was that the render was happening half in the api endpoint (the entries) and half in the representation namespace. Also drafts board was treated differently. I tried to remove this diversification and make sure all the rendering happens in the representation.
To test:
- test AP
- test AP pagination
- test FU
- test FU pagination
- add a new board
- edit the board settings (name, access, private users, private user roles)
- delete the board
- add a private board
- add other authors and viewers after creations
- check the authors and viewers are returned with the proper data (user-id and remove link)
- add a draft to the board
- publish a post to the board
- add a …

Fix board creation

---

src/oc/storage/representations/org.clj

Avoid sending reminders link to viewers, make sure they don't have private boards with edit permissions.
To test:
- invite a viewer
- accept invite
- do you not see the link with "reminders" rel in the org response?
- do you not see the Recurring updates item in the menu?
- now with the initial user add a private board
- add the viewer to the private board as viewer only
- refresh the viewer page
- do you not see the link with "reminders" rel in the org response?
- do you not see the Recurring updates item in the menu?
- now with the initial user change the viewer role in the private board to contributor
- refresh the viewer page
- do you see the link with "reminders" rel in the org response?
- do you see the Recurring updates item in the menu?

Viewers reminders link

---

src/oc/storage/db/common.clj
src/oc/storage/db/migrations/1580143129669_add_comment_index.edn

Add 2 indexes to the interactions table:
- resource-uuid-comment: used to filter on only comments of a certain post, used from the section pagination query and the inbox query
- created-at: used to get the bigger created-at when trying to calculate the last-activity-at value
Also changes how the filter/sort are applied in the queries (AP, section and inbox):
- apply filter on allowed boards before calculating the last-activity-at (for inbox query filter also on user unfollows)
- use max instead of sort/nth 0 to get the last comment created-at
- use the new resource-uuid-comment index to get all the comments
Is this the right place to add migration for the `interactions` table?
I added it here because it's used only here, but all migrations for this table are in open-company-interactions …

Single query performance improvements

---

project.clj
src/oc/storage/db/migrations/1581013849396_fix_resource_uuid_comment_index.edn

Bug: right now resource-uuid-comment return reactions as comments too.
This removes the index and recreate it with the right expression to calculate the boolean value for comments/reactions.
To test:
- add a post with user A
- add a comment with user B
- user A opens the post
- user B react to the post
- before this user A would have seen the post in Unread
- after he shouldn't

Fix resource-uuid-comment index

---

src/oc/storage/db/migrations/1582043152198_bookmarks_cleanup.edn
src/oc/storage/representations/entry.clj
src/oc/storage/resources/board.clj
src/oc/storage/resources/common.clj
src/oc/storage/resources/entry.clj

This PR is intended to:
- delete all `:follow-ups` data from entries
- remove follow-ups representation keys
- remove follow-ups render keys
- remove follow-ups retrieve functions
To test:
- before switching to this branch identify at least a post with `:follow-ups` data in it
- switch to this branch and start storage
- check that entry has no `:follow-ups` key anymore
- try opening that entry on web client
- no errors on web or storage?

Follow-ups cleanup

---

src/oc/storage/resources/common.clj
src/oc/storage/resources/org.clj

Supports https://github.com/open-company/open-company-web/pull/1158

Allow storing `utm-data` map in the org if it's provided at org creation
